# -*- coding: utf-8 -*-
"""Gaydar

Automatically generated by Colab.


# Train the Gaydar YOLO Model in Google Colab
**Original Author:** Evan Juras, [EJ Technology Consultants](https://ejtech.io)


**GitHub:** [Train and Deploy YOLO Models](https://github.com/EdjeElectronics/Train-and-Deploy-YOLO-Models)



**GitHub:** [Gaydar YOLO Model](https://github.com/courtschives/gaydar)

# Introduction

This notebook uses [Ultralytics](https://docs.ultralytics.com/) to train YOLO11, YOLOv8, or YOLOv5 object detection models with a custom dataset. At the end of this Colab, you'll have a custom YOLO model that you can run on your PC, phone, or edge device like the Raspberry Pi.

<p align=center>
<a href="https://youtu.be/r0RspiLG260" target="_blank"><br>
<i>Click here to go to the video!</i></a>
</p>


### Working in Colab
Colab provides a virtual machine in your browser complete with a Linux OS, filesystem, Python environment, and best of all, a free GPU. We'll install PyTorch and Ultralytics in this environment and use it to train our model. Simply click the Play button on sections of code in this notebook to execute them on the virtual machine.

**Verify NVIDIA GPU Availability**

Make sure you're using a GPU-equipped machine by going to "Runtime" -> "Change runtime type" in the top menu bar, and then selecting one of the GPU options in the Hardware accelerator section. Click Play on the following code block to verify that the NVIDIA GPU is present and ready for training.
"""

!nvidia-smi

"""# 3.&nbsp;Install Requirements (Ultralytics)

Next, we'll install the Ultralytics library in this Google Colab instance. This Python library will be used to train the YOLO model.
"""

!pip install ultralytics

"""#1.&nbsp;Gather and Label Training Images

# 2.&nbsp;Upload Image Dataset and Prepare Training Data

**Option 1. Upload through Google Colab**

Upload the `data.zip` file to the Google Colab instance by clicking the "Files" icon on the left hand side of the browser, and then the "Upload to session storage" icon. Select the zip folder to upload it.

<p>
<br>
<img src="https://raw.githubusercontent.com/EdjeElectronics/Train-and-Deploy-YOLO-Models/refs/heads/main/doc/upload-colab-files.png" height="240">
</p>

## 2.2 K-Fold Split and Train

At this point, whether you used Option 1, 2, or 3, you should be able to click the folder icon on the left and see your `data.zip` file in the list of files. Next, we'll unzip `data.zip` and create some folders to hold the images. Run the following code block to unzip the data.
"""

# Unzip images to a custom data folder
!unzip -q /content/drive/MyDrive/ColabNotebooks/gaydarMaterial/data.zip -d /content/drive/MyDrive/ColabNotebooks/gaydarMaterial/custom_data

"""Ultralytics expects data organized into train and val folders, each containing an images and labels subfolder. With a small, imbalanced dataset like this one (under 300 images across 17 classes), a single static 90/10 split leaves some classes with only 1-2 validation instances — which makes metrics like mAP unreliable and noisy for those classes.

Instead, we use k-fold cross-validation: the dataset is split into k groups (folds). We train k separate models, each time using a different fold as the validation set and the rest as training data. This way, every image gets used for validation exactly once across the k runs, and averaging the results gives a much more trustworthy estimate of how well the model actually generalizes — especially for rare classes that would otherwise get evaluated on just a handful of images.

The code below creates a kfold folder containing fold_0 through fold_{k-1}, each with its own train/val split and its own data.yaml config, ready for training in the next steps.

## Training Parameters FYI
Now that the data is organized and the config file is created, we're ready to start training! First, there are a few important parameters to decide on. Visit my article on [Training YOLO Models Locally](https://www.ejtech.io/learn/train-yolo-models) to learn more about these parameters and how to choose them.

**Model architecture & size (`model`):**

There are several YOLO11 models sizes available to train, including `yolo11n.pt`, `yolo11s.pt`, `yolo11m.pt`, `yolo11l.pt`, and `yolo11xl.pt`. Larger models run slower but have higher accuracy, while smaller models run faster but have lower accuracy. I made a brief YouTube video that compares performance of different YOLO models on a Raspberry Pi 5 and a laptop with a RTX 4050 GPU, [check it out here to get a sense of their speed accuracy](https://youtu.be/_WKS4E9SmkA). If you aren't sure which model size to use, `yolo11s.pt` is a good starting point.

You can also train YOLOv8 or YOLOv5 models by substituting `yolo11` for `yolov8` or `yolov5`.


**Number of epochs (`epochs`)**

In machine learning, one “epoch” is one single pass through the full training dataset. Setting the number of epochs dictates how long the model will train for. The best amount of epochs to use depends on the size of the dataset and the model architecture. If your dataset has less than 200 images, a good starting point is 60 epochs. If your dataset has more than 200 images, a good starting point is 40 epochs.


**Resolution (`imgsz`)**

Resolution has a large impact on the speed and accuracy of the model: a lower resolution model will have higher speed but less accuracy. YOLO models are typically trained and inferenced at a 640x640 resolution. However, if you want your model to run faster or know you will be working with low-resolution images, try using a lower resolution like 480x480.
"""

import os, glob, shutil, yaml
from pathlib import Path
from sklearn.model_selection import KFold
from ultralytics import YOLO

# ---- Config ----
BASE = Path('/content/drive/MyDrive/ColabNotebooks/gaydarMaterial')
CUSTOM_DATA = BASE / 'custom_data'      # unzipped data.zip: images/, labels/, classes.txt
KFOLD_DIR = BASE / 'kfold'
K = 5
MODEL = 'yolo26s.pt'
EPOCHS = 60
IMGSZ = 640

# ---- Read classes ----
classes_txt = CUSTOM_DATA / 'classes.txt'
with open(classes_txt, 'r') as f:
    classes = [line.strip() for line in f if line.strip()]
nc = len(classes)

# ---- Gather image/label pairs ----
img_dir = CUSTOM_DATA / 'images'
lbl_dir = CUSTOM_DATA / 'labels'
images = sorted([p for p in img_dir.glob('*') if p.suffix.lower() in ('.jpg', '.jpeg', '.png')])
print(f'Found {len(images)} images, {nc} classes')

# ---- K-fold split ----
kf = KFold(n_splits=K, shuffle=True, random_state=42)
fold_results = []

for fold_idx, (train_idx, val_idx) in enumerate(kf.split(images)):
    fold_dir = KFOLD_DIR / f'fold_{fold_idx}'
    if fold_dir.exists():
        shutil.rmtree(fold_dir)

    for split_name, idxs in [('train', train_idx), ('val', val_idx)]:
        (fold_dir / split_name / 'images').mkdir(parents=True, exist_ok=True)
        (fold_dir / split_name / 'labels').mkdir(parents=True, exist_ok=True)
        for i in idxs:
            img_path = images[i]
            lbl_path = lbl_dir / (img_path.stem + '.txt')
            shutil.copy(img_path, fold_dir / split_name / 'images' / img_path.name)
            if lbl_path.exists():
                shutil.copy(lbl_path, fold_dir / split_name / 'labels' / lbl_path.name)

    # ---- Write data.yaml for this fold ----
    data_yaml_path = fold_dir / 'data.yaml'
    data = {
        'path': str(fold_dir),
        'train': 'train/images',
        'val': 'val/images',
        'nc': nc,
        'names': classes
    }
    with open(data_yaml_path, 'w') as f:
        yaml.dump(data, f, sort_keys=False)

    print(f'\n===== Fold {fold_idx+1}/{K}: {len(train_idx)} train / {len(val_idx)} val images =====')

    # ---- Train ----
    model = YOLO(MODEL)
    results = model.train(
        data=str(data_yaml_path),
        epochs=EPOCHS,
        imgsz=IMGSZ,
        project=str(fold_dir),
        name='train'
    )

    # ---- Validate (grabs per-class metrics for this fold) ----
    metrics = model.val(data=str(data_yaml_path))
    fold_results.append(metrics.box.map50)  # overall mAP50 for this fold

# ---- Summary across folds ----
print('\n===== K-Fold Summary =====')
for i, m in enumerate(fold_results):
    print(f'Fold {i+1}: mAP50 = {m:.3f}')
avg_map50 = sum(fold_results) / len(fold_results)
print(f'\nAverage mAP50 across {K} folds: {avg_map50:.3f}')

"""The training algorithm will parse the images in the training and validation directories and then start training the model. At the end of each training epoch, the program runs the model on the validation dataset and reports the resulting mAP, precision, and recall. As training continues, the mAP should generally increase with each epoch. Training will end once it goes through the number of epochs specified by `epochs`.

> **NOTE:** Make sure to allow training to run to completion, because an optimizer runs at the end of training that strips out unneeded layers from the model.

The best trained model weights will be saved in `content/runs/detect/train/weights/best.pt`. Additional information about training is saved in the `content/runs/detect/train` folder, including a `results.png` file that shows how loss, precision, recall, and mAP progressed over each epoch.

#6.&nbsp;Test Model

The model has been trained; now it's time to test it! The commands below run the model on the images in the validation folder and then display the results for the first 10 images from eahc of the 5 models. This is a good way to confirm your model is working as expected. Click Play on the blocks below to see how your model performs.
"""

import glob
from pathlib import Path
from IPython.display import Image, display

BASE = Path('/content/drive/MyDrive/ColabNotebooks/gaydarMaterial')
KFOLD_DIR = BASE / 'kfold'
K = 5

for fold_idx in range(K):
    fold_dir = KFOLD_DIR / f'fold_{fold_idx}'
    weights = fold_dir / 'train-2' / 'weights' / 'best.pt'
    val_images = fold_dir / 'val' / 'images'

    print(f'\n===== Fold {fold_idx} predictions =====')

    !yolo detect predict model={weights} source={val_images} save=True project={fold_dir} name=predict

    pred_dir = fold_dir / 'predict'
    for image_path in glob.glob(f'{pred_dir}/*.jpg')[:10]:
        display(Image(filename=image_path, height=400))
        print('\n')

"""# Train Final Model
This trains one model on the entire dataset (no validation splits) with larger model and more epochs.
"""

import yaml
from pathlib import Path
from ultralytics import YOLO

# ---- Config ----
BASE = Path('/content/drive/MyDrive/ColabNotebooks/gaydarMaterial')
CUSTOM_DATA = BASE / 'custom_data'   # full dataset: images/, labels/, classes.txt
MODEL = 'yolo26l.pt'
EPOCHS = 120
IMGSZ = 640

# ---- Read classes ----
classes_txt = CUSTOM_DATA / 'classes.txt'
with open(classes_txt, 'r') as f:
    classes = [line.strip() for line in f if line.strip()]
nc = len(classes)

# ---- Write data.yaml pointing train AND val at the full dataset ----
data_yaml_path = BASE / 'data_final.yaml'
data = {
    'path': str(CUSTOM_DATA),
    'train': 'images',
    'val': 'images',   # same as train — metrics here are just a sanity check, not evaluation
    'nc': nc,
    'names': classes
}
with open(data_yaml_path, 'w') as f:
    yaml.dump(data, f, sort_keys=False)

print(f'Training final model on full dataset: {len(list((CUSTOM_DATA / "images").glob("*")))} images, {nc} classes')

# ---- Train final model ----
model = YOLO(MODEL)
model.train(
    data=str(data_yaml_path),
    epochs=EPOCHS,
    imgsz=IMGSZ,
    project=str(BASE / 'final_model'),
    name='train'
)

"""#7.&nbsp;Deploy Model

Now that your custom model has been trained, it's ready to be downloaded and deployed in an application! YOLO models can run on a wide variety of hardware, including PCs, embedded systems, and phones. Ultralytics makes it easy to convert the YOLO models to various formats (`tflite`, `onnx`, etc.) and deploy them in a variety of environments.

This section shows how to download the model and provides links to instructions for deploying it on your PC and edge devices like the Raspberry Pi.

## 7.1 Download YOLO Model

First, zip and download the trained model by running the code blocks below.

The code creates a folder named `my_model`, moves the model weights into it, and renames them from `best.pt` to `my_model.pt`. It also adds the training results in case you want to reference them later. It then zips the folder as `my_model.zip`.
"""

# Commented out IPython magic to ensure Python compatibility.
# Create "my_model" folder to store model weights and train results
!mkdir /content/my_model
!cp /content/runs/detect/train/weights/best.pt /content/my_model/my_model.pt
!cp -r /content/runs/detect/train /content/my_model

# Zip into "my_model.zip"
# %cd my_model
!zip /content/my_model.zip my_model.pt
!zip -r /content/my_model.zip train
# %cd /content

# This takes forever for some reason, you can also just download the model from the sidebar
from google.colab import files

files.download('/content/my_model.zip')